### ISSUE TITLE
Je potřeba wiki?

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#10]
Wiki nemá zrovna největší návštěvnost. Stálo by za to ji celou projít a zjistit, jestli je na ní vůbec něco zajímavého. Vhledem k minimální aktivitě v historii úprav hádám, že většina obsahu bude zastaralá.

**Comment by MikkCZ** [comment]
Prošel jsem wiki a zjistil, že možná přes polovinu článků jsou kopie z wiki.ubuntu.cz. Hlavně články o programech a základy společné pro vše na Ubuntu. Zkopírované nejsou články o prostředích, přímo o Mintu, souborových systémech a GRUBu.

Návštěvnost je asi 40-50 lidí za den. Návštěvy jsou 22% na hlavní stránce, 15% instalační návod, 4% instalace programů, 7% Cinnamon a Mate dohromady.

@sgflt máš nápad na nějakou revitalizaci wiki? V tomto stavu trochu pochybuji o přínosu hlavně těch zkopírovaných článků, pokud je na wiki Ubuntu lidi najdou i se spoustou dalších okolo. Chápu, wiki Ubuntu není wiki Mintu, ale stejně.

**Comment by sgflt** [comment]
Navrhoval bych smazání kopií (místo nich může být nějaký odkaz na Ubuntu jakožto distibuce, ze které Mint vychází) a ponechání obsahu týkajícího se konkrétně Mintu.

**Comment by MikkCZ** [comment]
> ÁNO - dnes je síce v hroznom, zanedbanom stave, ale raz sa možno nájde niekto, kto tomu vdýchne nový impulz, web aj fórum sú plné článkov a návodov, ktoré by tu mali byť, len ich sem nemá kto naplniť, samozrejme po primeranej úprave, nech to má jednotný vzhľad ak sa dá

**Comment by MikkCZ** [comment]
Mohli bychom vymyslet nějaký krátký textík s odkazem na wiki Ubuntu a postupně takové stránky nahrazovat. Při tom případně článek doplnit, pokud je u nás nějaká změna, nebo pokud si to prostě zaslouží. ;)

**Comment by redhawk75** [comment]
hm a co tak vytiahnut veci z clankov a tie tam nakopirovat (k terminalu, PGP ci veciam okolo kernelu je tam toho dost)

**Comment by AnickaT** [comment]
Wiki LinuxMintu je podle mého názoru potřeba určitě. Za mě ANO. Protože ne každý ví, že existuje ještě nějaký Ubuntu a jeho Wiki ;-) takže jsem pro aktualizaci, vylepšování a doplňování české Wiki Linux Mintu, souhlas s Kamowskim.

Možná další úkol: Napsat návod pro případné zájemce o aktualizaci Wiki LinuxMintu, plus témata tam k aktualizaci a doplnění. Třeba by se toho někdo ujal...

**Comment by MikkCZ** [comment]
Ponechme tedy wiki existovat a snad se najde čas ji dát zase nějak dohromady.
