### ISSUE TITLE
Je potřeba pokec?

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#11]
Nenašel jsem žádný záznam na serveru Jabbim, ale dalo by se odhadnout podle návštěvnosti stránky na webu.

**Comment by MikkCZ** [comment]
V průměru má pokec asi 5 návštěv za den.

**Comment by sgflt** [comment]
Kdysi dávno jsem tam byl i online, ale teď už není tolik času. Jestli tam nikdo nesedí nonstop, tak je pokec nahraditelný fórem.

**Comment by MikkCZ** [comment]
> NIE - na fórum príde najčastejšie človek hľadať riešenie a chce ho "UŽ AJ" ale toto nie je platená podpora ani služba eshop-u, tu nemá kto sedieť a radiť

**Comment by redhawk75** [comment]
podla mna nie je to treba. bol som tam raz pozriet.

**Comment by AnickaT** [comment]
Podle mě taky není nutný online chat, zvláště když tam nikdo není... Od toho jsou komunikátory jako Pidgin apod. Myslím si, že ten kdo hledá pomoc online chat nevyužije... zvlášť když je tam skoro furt prázdno.

**Comment by MikkCZ** [comment]
Nastavme tedy přesměrování URL na fórum.

**Comment by MikkCZ** [comment]
Přesměrováno.
