### ISSUE TITLE
Editor článku

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#12]
Už nevím od koho jsem dostal podnět na zlepšení editoru pro psaní článků na webu.

**Comment by MikkCZ** [comment]
> editovať články na webe je katastrofa, takže ÁNO, ak je to možné zmeniť

**Comment by redhawk75** [comment]
suhlasim s kamowskim, niekedy upravit clanok najma ak chcem formatovat text je utrpenie

**Comment by AnickaT** [comment]
Jo, určitě zlepšit editor článků. Za mě ano.

**Comment by MikkCZ** [comment]
@redhawk75 @AnickaT Co vám konkrétně v editoru nevyhovuje/chybí/přebývá? Co používáte při psaní nejčastěji?

**Comment by MikkCZ** [comment]
@redhawk75 @AnickaT Co vám prosím v editoru nevyhovuje/chybí/přebývá? Co používáte při psaní nejčastěji? Bez toho ho nijak zlepšit nedokážu, když se to nedozvím.

Na webu už je nainstalovaný nějaký plugin pro pokročilejší možnosti úprav. Není to naopak tím, kolik je v něm tlačítek? Ten základní umí jenom formát textu (b, i, seznamy, citace, zarovnání textu a odkaz, nic moc víc). A samozřejmě vložit obrázek.
