### ISSUE TITLE
phpBB > bbPress

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#13]
V záznamech vidím, že se občas lidi z fóra snaží přihlásit stejnými údaji na web. Možná by stálo za průzkum, jestli a jaké funkce phpBB nejvíc používáme a zda by nestačilo použít bbPress (plugin do WordPressu) podobně jako je použit na separatista.net. O jeden systém na údržbu méně.

**Comment by MikkCZ** [comment]
od skrob:
Dobrý den,
dle mne forum jede jak má, nastavení spousta, přihlášení bez problémů, tvorba avataru taky v klidu, vkládání obrázků bez problémů, výborné vyhledávání....aktivní, moje, poslední atd. a chválím zobrazení na hlavních stránkách s náhledem posledních příspěvků. Z mé stránky uživatele mne nenapadá nedostatek.
s pozdravem skrob

**Comment by MikkCZ** [comment]
> prihlásenie na web aj fórum jedným heslom - NIE - na web by mali byť pustení len "schválení" autori

**Comment by MikkCZ** [comment]
Tady jsem zapomněl říct, že registrovat a přihlásit se jde na webu i teď. Jdou díky tomu posílat soukromé zprávy nebo komentáře pod registrovaným účtem. Jsou to vlastně všichni zde https://www.linux-mint-czech.cz/members/. Přístup k psaní článků ale nemají.

**Comment by AnickaT** [comment]
Souhlas s Kamowskim. Přihlášení na web i fórum jedním heslem: NE. Na web mají přispívat "schválení" autoři, tedy určitý okruh lidí co může psát články, ne kdokoliv. Už tak na webu je trollingu v komentech ažaž.
Radši omezit trolly na webu v komentech, popřípadě jejich debilní komentáře bez pardonu průběžně mazat.

**Comment by AnickaT** [comment]
Jinak s fórem LinuxMint spokojenost, nemám co vytknout.

**Comment by redhawk75** [comment]
no prave ze niekedy tie komenty mam chut mazat, ale nemazem. ale ano prechod na bbPress pokial nebude moc obmedzovat forum je OK, ale horsie aby sa potom nezvrtli veci pod clankami

**Comment by AnickaT** [comment]
Tak proč přecházet na bbPress, když nevíme zda to neovlivní komenty pod články. Spíš to průběžně promazávat (trolly).

**Comment by redhawk75** [comment]
pravda.

**Comment by MikkCZ** [comment]
Viz můj předchozí [komentář](https://github.com/linux-mint-czech/ukoly/issues/13#issuecomment-264398529) - na web se už teď může registrovat kdo chce, ale psát články nemůže. Je to vlastně jen přihlášení pro komentáře případně posílání soukromých zpráv.

**Comment by MikkCZ** [comment]
V tuto chvíli necháme současný systém phpBB.
