### ISSUE TITLE
Tisk článků na webu

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#14]
> chýba tlačítko "Tlač" pri článkoch

**Comment by redhawk75** [comment]
alebo export do pdf

**Comment by AnickaT** [comment]
Tisknout články rovnou jedním tlačítkem by bylo určitě fajn. :-) Za mě ano.

**Comment by MikkCZ** [comment]
Přidal jsem tlačítko vpravo do záhlaví články.
