### ISSUE TITLE
Přeorganizovat rubriky

### ISSUE THREAD

**Issue by redhawk75** [linux-mint-czech/ukoly-a-wiki#15]
Mna napadla jedna vec, upravit kategorie clankov.
Privela kategorii, stacilo by to nejako ucesat, urcite novinky, serialy, tutorial, navody a ostatne. k tomu povedzme dopisat, ale aby tam nebolo 300 zaloziek. Zacina to bytž neprehladne.

**Comment by MikkCZ** [comment]
Aktuálně jsem smazal štítky bez článků (zbylo 38). Rubrik je 47, z toho ale jen 10 má méně než 10 článků. Je otázka jestli nejsou nějaké duplicitní nebo některé články nejsou zbytečně v mnoha rubrikách. Nechceš se na to podívat @redhawk75 a navrhnout možné kroky? Klidně ti pak přidám práva to provést, pokud je nemáš.

**Comment by redhawk75** [comment]
Ahoj,

ak to je aktualne, pozriem.

Opravnenia netusim.


Redhawk


________________________________
Od: Michal Stanke <notifications@github.com>
Odoslané: 12. marca 2017 19:15
Komu: linux-mint-czech/ukoly
Kópia: Red Hawk; Mention
Predmet: Re: [linux-mint-czech/ukoly] kategorie clankov (#15)


Aktuálně jsem smazal štítky bez článků (zbylo 38). Rubrik je 47, z toho ale jen 10 má méně než 10 článků. Je otázka jestli nejsou nějaké duplicitní nebo některé články nejsou zbytečně v mnoha rubrikách. Nechceš se na to podívat @redhawk75<https://github.com/redhawk75> a navrhnout možné kroky? Klidně ti pak přidám práva to provést, pokud je nemáš.

**Comment by MikkCZ** [comment]
Ano, stále je to aktuální. ;)

**Comment by MikkCZ** [comment]
Aktuální návrh:
> Linux MINT - novinky k Mintu,
> Novinky / bleskovky - news mimo Mint (Devuan, Debian, Ubuntu a pod),
> Software - programy, DE,
> Tipy a triky
> Všeobecné - nezaraditelne

**Comment by redhawk75** [comment]
podla mna dobre
