### ISSUE TITLE
Doména linux-mint.cz

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#17]
Co s ní?

**Comment by redhawk75** [comment]
nebolo by lepsie ju pouzivat? namiesto linux-mint-czech.cz ?

**Comment by MikkCZ** [comment]
Uvažoval jsem o tom, stálo by to dost přesměrování a trochu práce s migrací webu a subdomén na novou doménu, ale jinam by to asi nebyl problém.

**Comment by MikkCZ** [comment]
Ideální by bylo mít doménu linuxmint.cz (bez pomlčky).

**Comment by MikkCZ** [comment]
Podařilo se mi domluvit s vlastníkem linuxmint.cz a ta je nyní přesměrovaná na linux-mint-czech.cz.

**Comment by MikkCZ** [comment]
Jsou tedy tři možnosti:
- přesunout se na doménu linuxmint.cz, která bude kratší a mnohem lépe zapamatovatelná, ale v registru bude jiný vlastník
- přesunout se na doménu linux-mint.cz, která bude také kratší, ale nebude to úplně ono :)
- zůstat na linux-mint-czech.cz, která je dlouhá a navíc obsahuje i "czech", přestože v hlavičce webu píšeme "CZ&SK"

Sám bych klidně šel do první varianty. Pan Orkáč vypadá v pohodě a těch domén má podobným způsobem víc.

**Comment by MikkCZ** [comment]
^ Co myslíte ostatní? @AnickaT @KOLEGA007 @redhawk75 @sgflt

**Comment by ondrejkolin** [comment]
linuxmint.cz mi přijde lepší, protože je tady vazba na "linuxmint.com". Ovšem vím, že když jsem kdysi dávno jednal, tak chtěl řešit případné merchandising. Pokud mu věříš, udělal bych přesun.

**Comment by MikkCZ** [comment]
> ak sa jej nechce vzdať v prospech komunity, by som neveril ani pozdrav

**Comment by AnickaT** [comment]
Doména linuxmint.cz je IMHO ideální název: je jasný o jakej Linux jde (distro) a CZ jasně označuje českej web i počeštěnou verzi LinuxMintu.

**Comment by sgflt** [comment]
Podle mě není žádoucí, aby vlastník domény byl mimo komunitu. To tak můžeme převést web na linuxmint.cz a za týden tam bude něco jiného. Takže bych byl v tomto ohledu opatrný. Doména je sice hezká, ale nějaké záruky jsou nutné.

**Comment by MikkCZ** [comment]
S ohledem na kritické hlasy to nechme beze změny.
