### ISSUE TITLE
plánovanie článkov

### ISSUE THREAD

**Issue by redhawk75** [linux-mint-czech/ukoly-a-wiki#18]
už asi 10 dní je problém s naplánovaním zverejnenia príspevku.
Čas prejde a ostane stav zmeškané.

**Comment by MikkCZ** [comment]
WordPress cron je vypnutý (kvůli vytížení) a spouští se periodicky každé dvě hodiny. Tzn. článek se publikuje, ale možná až s dvouhodinovým zpožděním. Zařídím spouštění po 15 minutách.

**Comment by redhawk75** [comment]
VDaka za info, netreba menit interval. len teraz viem, budem spustat publikovanie rucne

**Comment by MikkCZ** [comment]
Cron od včerejška běží s intervalem 15 minut. Plánování se tedy opozdí o 15 minut, ale fungovat bude. Není potřeba publikovat ručně.
