### ISSUE TITLE
Blokování IP adres na www

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#2]
Je ještě potřeba po nasazení Cloudflare?

**Comment by sgflt** [comment]
Nejspíš ne. Může se to zkusit vypnout.

**Comment by MikkCZ** [comment]
Zkusmo jsem deaktivoval. Uvidíme.

**Comment by MikkCZ** [comment]
Fungujeme bez většího množství spamu v komentářích nebo registracích i bez blokování. ;)
