### ISSUE TITLE
Aktualizovat phpBB na řadu 3.2

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#20]
Vyzkoušel jsem migraci podle https://www.phpbb.com/support/docs/en/3.2/ug/upgradeguide/upgrade3/. Všechno v pořádku, jen bude potřeba udělat nový vzhled. Podobný současnému by neměl být problém vytvořit na základě https://www.phpbb.com/customise/db/style/allan_style_subsilver/.

- [x] aktualizace na phpBB 3.2
- [x] nasazení nového vzhledu
- [x] Google Analytics plugin
- [x] promazat cache

Bude vyřešeno samostatně:
- přidat plugin pro označení jako vyřešené (#21)
- Tapatalk (#19)
- služba pro nahrávání snímků (#6)

**Comment by MikkCZ** [comment]
Po aktualizaci bude potřeba opravit #21, #19 a #6.

**Comment by MikkCZ** [comment]
A taky #19.

**Comment by MikkCZ** [comment]
Kód aktuální šablony je na https://github.com/linux-mint-czech/subsilver2 a v historii commitů jsou vidět změny provedené oproti standardnímu subsilver2.

**Comment by MikkCZ** [comment]
Začal jsem připravovat šablonu pro phpBB 3.2. https://github.com/linux-mint-czech/lmcz-subsilver

**Comment by MikkCZ** [comment]
Šablona je víceméně připravená a k nahlédnutí na https://forumtest.linux-mint-czech.cz/. @AnickaT co na to říkáš?

**Comment by AnickaT** [comment]
Díky, vypadá to pěkně. Bude možnost volit i jiný než zelený vzhled (třeba modrý) jako to je na fóru dosud? A příspěvky s odpověďmi na původním fóru zůstanou naimportovány? Díky za odpovědi.

**Comment by MikkCZ** [comment]
Udělám jenom aktualizaci na verzi 3.2 a přitom nasadím tento "nový" vzhled. Všechna data a i nastavení, pokud dávají smysl, zůstanou zachována. Příspěvky i uživatelské účty zůstanou beze změny, jenom to bude znamenat asi hodinu nedostupné fórum.

Zatím jsem neplánoval dělat modrou variantu vyloženě této úpravy, ale určitě půjde zapnout výchozí vzhled phpBB prosilver (https://www.phpbb.com/customise/db/style/prosilver/demo/3.2) a subsilver (https://www.phpbb.com/customise/db/style/allan_style_subsilver/demo/3.2), ze kterého ten Mintí vychází. Ten výchozí prosilver na současné instalaci používají 3 lidé.

**Comment by MikkCZ** [comment]
Pokud nebudou žádné vážné připomínky, udělám aktualizaci tento pátek nebo o víkendu.

EDIT: Možná bych to stihl už ve čtvrtek večer. :)

**Comment by MikkCZ** [comment]
Nová verze je na svém místě a všechno zdá se šlape stejně nebo lépe než předtím.
