### ISSUE TITLE
Hlášení nevhodných komentářů

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#24]
> nebolo by od veci mať aj tlačidlo "Nahlásiť nevhodný komentár"
> editovať komentáre pod článkom môže iba autor článku alebo admin
> niekoľkoročné články (nenechavci ich oživujú) autor ktorých už dnes nemusí navštevovať tento web, tak by to bolo hlásené adminovi

**Comment by redhawk75** [comment]
no toto zacina v poslednom case byt dost akutne, a aj vo fore nam zacali obcas vyskakovat spamy

**Comment by MikkCZ** [comment]
Hlášení příspěvků na fóru existuje a ty nahlášené by měli vidět moderátoři. Každopádně než se hlášení přidá, je potřeba si ujasnit pravidla (https://forum.linux-mint-czech.cz/viewforum.php?f=10 ?) a mít někoho, kdo budu nahlášené komentáře alespoň jednou za týden kontrolovat a s chladnou hlavou řešit. Nechci žádnou totalitní cenzuru.

Možná by trochu pomohlo povolit komentáře jenom po registraci...

**Comment by redhawk75** [comment]
> Možná by trochu pomohlo povolit komentáře jenom po registraci..
Asi ano.

Jasne ze nie cenzuru, len je tam spam a stale pokojne vysi :-) komentare ma netrapia,.

**Comment by MikkCZ** [comment]
Přidal jsem na web možnost hlášení komentářů (odkaz přímo pod komentářem). Pokud bude nějaký nahlášen třikrát, plugin ho automaticky schová a pošle mi e-mail.
