### ISSUE TITLE
Zobrazení počtu návštěv článku v administraci

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#25]
Návštěvnost na straně serveru sleduje plugin WordPress Popular Posts a pak ještě Google Analytics.

**Comment by MikkCZ** [comment]
Ani jeden z pluginů to zřejmě neumí. Jsou zde dvě možnosti
- zajistit pro všechny autory, kteří budou mít zájem, přístup do statistik, klidně skrze nástěnky, co který plugin v administraci umí
- nahradit jiným pluginem, který toto umět bude, např. WP Statistics to myslím zvládá

@sgflt používáme vlastně GA nějak více do hloubky, nebo prostě jenom máme nastaveno? Myslím hlavně web, pro wiki a fórum teď asi není rozumná náhrada.

**Comment by sgflt** [comment]
GA se do hloubky zatím nijak nepoužíval. Sloužil spíše jen jako porovnání návštěvnosti mezi měsíci.

**Comment by MikkCZ** [comment]
Pojďme se tedy GA zbavit a nahradit něčím ve WordPressu. Historická data importovat asi nepůjde, ale to asi nevadí.

**Comment by MikkCZ** [comment]
@redhawk75 můžeš se prosím podívat, jestli máš přístup v administraci na https://www.linux-mint-czech.cz/wp-admin/options-general.php?page=wordpress-popular-posts?

**Comment by MikkCZ** [comment]
Podařilo se mi jiným pluginem přidat data z GA přímo do seznamu článků v administraci.
