### ISSUE TITLE
Odebrat ikony operačního systému a prohlížeče

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#30]
Je toto vůbec něco, co chceme u komentářů zobrazovat? Dneska už to není moc běžné a z mého pohledu to trochu zavání omezováním soukromí návštěvníků.

**Comment by MikkCZ** [comment]
Zatím jsem upravil nastavení, aby se nezobrazovaly verze.

**Comment by MikkCZ** [comment]
@sgflt Co si o tom myslíš, mají tyhle ikonky nějaký smysl?

**Comment by sgflt** [comment]
Ikony mají smysl možná tak pro rozpoutání flame war, takže mohou klidně zmizet.
