### ISSUE TITLE
Témata Linux Mint

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#32]
Přímo ve fóru [Linux Mint](https://forum.linux-mint-czech.cz/viewforum.php?f=8&start=25) je asi 39 témat (nezatříděných) a zbylých přes 2000 je v subfórech. Ta samostatně stojící bychom měli přesunout taktéž do subfór a z fóra Linux Mint udělat kategorii, kam se nedá přímo zakládat nová témata. Co myslíš @AnickaT?

**Comment by AnickaT** [comment]
Diky. Urcite je fajn roztridit 39 nezatridenych temat/threadu pokud maji i odpoved(i).

**Comment by AnickaT** [comment]
Forum Linux Mint ma IMHO dost zakladnich kategorii (lidove "temat" , presneji subfor), takze nove kategorie ve foru by mohli zakladat jen Admin a Moderatori, bezni uzivatele ne.

**Comment by MikkCZ** [comment]
Hotovo.
@AnickaT: Kdyžtak můžeš třídit špatně umístěná témata i sama přes moderátorské nástroje. Nejrychlejší je to asi dole pod tématem po klepnutí na tlačítko s kladívkem a "Přesunout téma". Doporučuju nechávat stínová tématu v původním subfóru, pokud by to někdo hledal na původním místě.
