### ISSUE TITLE
Pravidla pro diskuze na webu

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#39]
V reakci na některé komentáře se objevila potřeba vytvořit pravidla pro diskuze na webu a určit jim meze.

**Comment by MikkCZ** [comment]
@AnickaT @kamowski, co si myslíte o současných pravidlech na fóru? Daly by se v nějaké upravené verzi použít pro komentáře, pokud je tedy o to zájem?

**Comment by kamowski** [comment]
ahoj,

komentáre pod články je možné písať bez registrácie, tak neviem, či má zmysel písať niekam nejaké pravidlá
kto by si ich prečítal?
a ak s nimi nesúhlasí? ... aj tak môže napísať komentár

myslím, že nie je nutné všetko regulovať predpismi, písanými pravidlami,
ľudia by mali byť v prvom rade vychovaní, slušní, mali by dodržiavať nejakú etiku, mantinely spoločenského správania sa, ..., z princípu
ak majú v tomto nedostatky a aj napriek tomu, že sú gramotní, nevedia/nechcú slušne a vecne komunikovať s inými ľuďmi, žiadne písané pravidlá nepomôžu

... a komentáre pod článkom si môže a MUSÍ ustrážiť autor článku, **je to jeho článok a on moderuje diskusiu pod ním**
žiadne slniečkárstvo, liberalizmus a podobné sprostosti  tu nemá miesto, žiadne fňukanie o cenzúre nie je namieste,
to je ako v práci, žiadna demokracia na pracovisku neplatí, tam sú iné pravidlá, inak je to anarchia
bez kompromisu môže mazať !

:)

**Comment by MikkCZ** [comment]
Napsat může, ale bez pravidel to bude taková džungle, kdo co smaže nebo nesmaže. Je potřeba si uvědomit, že jednak jakákoliv pravidla omezují, co smí kdo napsat, ale také určují meze moderátorovi, protože nebude mít těmi pravidly povoleno třeba smazat komentář, který se článkem nesouhlasí.

Ano, ale pořád tam pravidla jsou. My teď žádná nemáme.

**Comment by kamowski** [comment]
doteraz to bolo bez písaných pravidiel a fungovalo to
tak teraz neviem, čo chceš dosiahnuť, 
obmedziť moderátora? nastaviť mu mantinely?
u nás sa policajt bojí zasiahnuť, aby ostal medzi mantinelmi, je to zlé, je to falošné a zlé, určite sa to vypomstí
na svojom webe si JA určujem pravidlá, pod svojim článkom JA moderujem diskusiu, 
kto s tým má problém, nech si vytvorí vlastný web a napíše vlastný článok
JA určujem mantinely, 
áno možno zmažem aj komentár, ktorý ako ty píšeš, nesúhlasí so mnou, ale to je moje výsostné právo, ako autor môžem vôbec NEPOVOLIŤ diskusiu, ak si to neprajem, umožňuje to obslužný sw a mám na to aj morálne právo
bodka
howg
:)
pýtal si sa na názor, napísal som ho a stojím si za tým
ale aj tak urobíš, ako uznáš za vhodné, ty si správca a zodpovedáš tu za to :)

**Comment by MikkCZ** [comment]
Nechme tedy ať diskuze moderuje každý pod vlastním článkem podle svého vlastního vědomí a svědomí.
