### ISSUE TITLE
Aktualizace phpBB

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#4]
V tuto chvíli blokování pluginem pro přihlašování pomocí sociálních sítí. Je třeba aktualizovat minimálně v rámci řady 3.0.

**Comment by sgflt** [comment]
Nešlo by přihlašování propojit i s hlavním webem? Aby si uživatelé nemuseli dělat dva a více účtů.

**Comment by MikkCZ** [comment]
Jednoduchý způsob by byla migrace z phpBB na bbPress (https://github.com/linux-mint-czech/ukoly/issues/13). Bylo by to ale trochu chudší fórum. Druhá možnost je integrace přes nějaký plugin (narychlo jsem našel https://wordpress.org/plugins/wp-phpbb-bridge/, https://wordpress.org/plugins/phpbb-unified-login/, https://wordpress.org/plugins/wp-w3all-phpbb-integration/, https://wordpress.org/plugins/wp-united/ a https://wordpress.org/plugins/phpbb-single-sign-on/).

**Comment by sgflt** [comment]
Pozor na dlouho nekatualizované pluginy. Většina z nich neměla přes 2 roky update. Buď jsou tak dobré, že to nepotřebují, nebo jsou neperspektivní.

**Comment by redhawk75** [comment]
o kolko by bolo bbPress chudsie?
Ak kvoli obrazkom riesit cez postimage. zaroven usetris priestor.

**Comment by AnickaT** [comment]
Přihlašování (na fórum) propojit s (hlavním) webem: Za mě určitě NE. Pak bude na web psát kdejaký troll.
