### ISSUE TITLE
príspevok vo fóre - zrušenie

### ISSUE THREAD

**Issue by kamowski** [linux-mint-czech/ukoly-a-wiki#40]
... začnem písať odpoveď do niektorého vlákna na fóre, potom si to z nejakého dôvodu rozmyslím
v tomto momente by som privítal tlačítko (bolo tu niekedy) "Zrušiť odpoveď"
vedel by si ho tam pridať?
ďakujem :)

**Comment by MikkCZ** [comment]
Není potřeba, rozepsaná odpověď se nikam neukládá, takže stačí kliknout na nějaký odkaz a jít pryč. Nebo co přesně by to tlačítko mělo udělat?

**Comment by kamowski** [comment]
áno, presne toto robím a je to také, ...., mám z toho blbý pocit :)
malo by ma vrátiť späť do toho vlákna, jeden, dva kroky" 
ja viem, o nič nejde, ale bolo by to také  "čistejšie"

**Comment by MikkCZ** [comment]
Takový odkaz udělat můžu, ale bude fungovat v 99% procentech případů stejně jako tlačítko zpět v prohlížeči. Spíš hůře, protože Zpět v prohlížeči použije keš. Btw. takový odkaz tam vlastně už je, stačí kliknout na velký nadpis názvu tématu pod záhlavím stránky.

**Comment by MikkCZ** [comment]
@kamowski stačí tlačítko zpět v prohlížeči nebo ten proklik přes nadpis?

**Comment by kamowski** [comment]
nechaj tak, zrejme to nikomu nevadí :)
