### ISSUE TITLE
Ukončit provoz webu

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#42]
Je zde otázka, jestli vůbec v provozu webu dál pokračovat, protože to celé tak nějak umřelo. Rozhodnutí se bude odvíjet i podle #41.

V případě ukončení webu:
- [ ] připravit kompletní zálohy pro případ, že by se hned objevila "nová komunita"
- [x] zachovat fórum
- [ ] archivovat web alespoň do web.archive.org
- [ ] zajistit vhodné přesměrování často navštěvovaných stránek
- [ ] web nahradit statickou stránkou s odkazy na stažení a alternativní weby
- [x] co s wiki, kde vlastně nic moc není? (#43)

**Comment by 1stein1975** [comment]
Ono umrelo, v podstate forum funguje to by bolo dobre ponechat.
Co sa tyka obsahu webu, problem je, ze 2-4 autori neutiahnu chod celeho portalu, vacsinou je problem cas.

**1.) připravit kompletní zálohy pro případ, že by se hned objevila "nová komunita"**
urcite ano.
**2.) zachovat fórum**
taktiez si myslim ze je to nutne, predsa len su vecio co v ubuntu idu a v minte nie a opacne.
**3.) co s wiki, kde vlastně nic moc není?**
presmerovat na eng alebo Ubuntu
**4.) archivovat web alespoň do web.archive.org**
to sa moze aj ked bude LM.cz fungovat dalej
**5.) zajistit vhodné přesměrování často navštěvovaných stránek**
netusim 
**6.) web nahradit statickou stránkou s odkazy na stažení a alternativní weby**
Skor nechat zaklad o minte, forum a linky na stiahnutie a na podporovane verzie. 

RedHawk

PS: A sakra z neznameho dovodu ma nalogovalo pod inym kontom do GITu

**Comment by redhawk75** [comment]
Este by som snad doplnil, ze vcelku pokojne by si mohol, ak to prevezme OpenAlt, nechat web tak ako je, s tym ze web by sa vzdy doplnil o nove verzie LM a linky na stiahnutie.

**Comment by MikkCZ** [comment]
Do dohody s OpenAltem nic dělat nebudu. Tohle je alternativa, pokud by to OpenAlt provozovat nemohl/nechtěl.

**Comment by kamowski** [comment]
Na linuxmint.com je to tiež také "zamrznuté", bude to tak, ako písal niekde redhawk75, nie sú témy
Na linuxmint.hu bola uverejnená výzva, že hľadajú autorov, bolo by dobré niečo také napísať aj tu na stránku, možno zistíme, že témy sú, len nám akosi chýba čas, motivácia, ..., sme vyhoretí
Na oboch spomínaných stránkach fórum veselo funguje
Začal by som tou výzvou, kto ju napíše? :)
p.s.: určite sa zhodneme na zachovaní fóra, takže s OpenAlt jednať môžeš, súhlasím s  redhawk75

**Comment by MikkCZ** [comment]
Zapomněl jsem postnout i sem, jaký je stav. Zrušil jsem wiki, protože ta byla mrtvá, respektive ji přesměroval na aktuálnější články a informace jinde. Samozřejmě mám zálohu. Fórum ani web se zatím rušit nebude. @snajpa buduje novou tajnou základnu pro linuxové komunity, ať už obecně nebo s prostorem pro jednotlivá distra, diskuze apod. Uvidíme, kam se to během pár mesíců posune.
