### ISSUE TITLE
pdf z článkov

### ISSUE THREAD

**Issue by kamowski** [linux-mint-czech/ukoly-a-wiki#45]

**Comment by kamowski** [comment]
vedel by si "vyrobiť" pdf-ko s článkami zverejnenými na stránke?
či už podľa ročníkov alebo aj v celku, to mi je vlastne jedno

**Comment by MikkCZ** [comment]
Myšlíš něco jako export všech článků do PDFka? Přímo ve WordPressu na to nic asi není, ale nějaký jednorázový skript by nemusel být problém?

**Comment by ghost** [comment]
skusal som to manualne - da sa to .
Je to pracne ale ked nebudem mat co robit tak mozem postupne.
Len aby som nerobil to co uz niekto urobil.
Kde ti mam poslat ukazku?
A s dikusiou alebo bez?

**Comment by kamowski** [comment]
ďakujem za reakciu.

manuálne si to robím doplnkom pre ff Convert WebPage To PDF, tento mi 
vyhovuje, lebo robí pdf aj s komentármi, čo je dôležité/žiaduce,
žiaľ, niektoré články už autori zmazali, takže sa k nim takto na stránke 
nedostanem, áno, na blogu redhawka sú tie jeho, vraj, ale iste bez 
komentárov, no čo už :(

ak by si sa nudil a prevedieš všetky do pdf, zlúč ich do "ročenky/ročeniek"
už to tu bolo, asi prvé dva roky, ak si dobre pamätám, možno sú niekde v 
archíve, admin by mohol vedieť

ukážku môžeš poslať na môj email ako prílohu
alebo otvor tému na fóre, možno sa niekto pridá alebo vie jednoduchšie 
riešenie alebo len jednoducho niečo ... oné ... a daj to ako prílohu tam

kamowski


Dňa 06.01.2018 o 09:06 petbar napísal(a):

**Comment by ghost** [comment]
ako myslis rocenku? ze jedno pdf za cely rok? to bude dost velke, nie?

Dňa 7. januára 2018, 14:56, kamowski <notifications@github.com> napísal(-a):

**Comment by MikkCZ** [comment]
Pokud je na to nějaký nástroj, rád s exportem do PDF pomohu. Ale nic jsem nenašel.
