### ISSUE TITLE
eshop

### ISSUE THREAD

**Issue by kamowski** [linux-mint-czech/ukoly-a-wiki#46]
ahoj,

pri čítaní vlákna na fóre: https://forum.linux-mint-czech.cz/viewtopic.php?t=3658&p=24526#p24526
som ostal prekvapený, zarazený, ..., no skrátka, bol som mimo a zrejme nie len ja
áno, eshop skutočne figuruje na hlavnej stránke aj keď s touto komunitou nemá vôbec nič spoločné (myslím)

nakoľko vôbec nemám prehľad, kto to tam spravuje, čo predáva a teda neviem za túto časť webu nijak zodpovedať a nemienim sa tomu začať teraz venovať, a ak aj vy ste na tom podobne, 
navrhujem tento odkaz z hlavnej stránky odstrániť, bez náhrady

kamowski

**Comment by kamowski** [comment]
ahoj,

pri čítaní vlákna na fóre: https://forum.linux-mint-czech.cz/viewtopic.php?t=3658&p=24526#p24526
som ostal prekvapený, zarazený, ..., no skrátka, bol som mimo a zrejme nie len ja
áno, eshop skutočne figuruje na hlavnej stránke aj keď s touto komunitou nemá vôbec nič spoločné (myslím)

nakoľko vôbec nemám prehľad, kto to tam spravuje, čo predáva a teda neviem za túto časť webu nijak zodpovedať a nemienim sa tomu začať teraz venovať, a ak aj vy ste na tom podobne, 
navrhujem tento odkaz z hlavnej stránky odstrániť, bez náhrady

kamowski

**Comment by MikkCZ** [comment]
Ahoj.

Odkaz je v menu a na stránce ke stažení docela dlouho a vede na linuxový e-shop LinuxMarket.cz Lukáše Jelínka (OpenOffice.cz, LinuxExress.cz, ...). Původně jsme uvažovali o zavedení nějaké obarvené verze e-shopu pro Mint s tím, že by se to dalo propojit s financováním webu apod., ale nakonec jsme se domluvili jenom na odkazu.

Pokud myslíš, že už není doba, kdy má pro někoho cenu si médium koupit místo jeho vypalování/nahrávání na flešku, klidně ty odkazy dám pryč.

**Comment by MikkCZ** [comment]
@kamowski chceme to tedy nějak dál řešit?
