### ISSUE TITLE
Zviditelnit vybrané články

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#5]
redhawk: Urcite by bolo dobre trochu upravit hlavne aby sa dali pridavat novinky, ktore by nespadali do clankov a boli by hore (ako info o kerneloch ci vydania Verzie)

@MikkCZ: S těmi novinkami myslíš, aby zůstávaly ve vlastním widgetu jako je třeba "Ze světa Open Source" vpravo na http://www.linux-mint-czech.cz/aktuality/, nebo přímo v tom seznamu článků?

redhawk: Ano aby mali vlastny widget. Tazko sa totiz novinky dohladavaju, kedze sa clanky miesaju v kope s novinkami a aktualizaciami

@MikkCZ: Udělat další widget nebude problém, ale asi by to chtělo vůbec více oddělit technické články od "blogů".

**Comment by AnickaT** [comment]
Souhlas: Oddělit návody - posty ("blogy") - informace ze světa LinuxMint (např. nová verze LM 18 apod.).

**Comment by MikkCZ** [comment]
V rámci #15 jsem přeorganizoval rubriky a udělal v článcích trochu pořádek. Zviditelněné teď budou Novinky a bleskovky, které se zobrazují v postranním widgetu. Také jsem mezitím zjednodušil hlavní stránku, kde je dole v patičce vidět vždy posledních pět článků.
