### ISSUE TITLE
Integrovat Postimage nebo podobnou službu pro nahrávání obrázků na fóru

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#6]

**Comment by MikkCZ** [comment]
> najprv som myslel, že treba umožniť nahrávať obrázky každému zaregistrovanému ale tade asi cesta nevedie, to by sa ľahko zneužilo a nie sú kapacity na to aby to niekto strážil, takže ÁNO, nech si to nahrajú na stránky, ktoré sa tomu venujú a vložia sem odkaz/náhľad
> zároveň by som nechal aj súčasnú možnosť, nahrať to na náš server

**Comment by MikkCZ** [comment]
Toto mi navrhoval už nevím kdo. Když jsem provoz převzal, akorát v podobný čas došlo k naplnění limitu pro nahrané soubory. Fórum má nastavený prostor, jak velké mohou být dohromady všechny přílohy. Zvětšit ho je jedno kliknutí myší, ale nechci tam zase dávat nějakou ohromnou kapacitu, kdyby se něco stalo. Externí služba by to mohla řešit.

**Comment by redhawk75** [comment]
ano to by bolo vhodne.
Napriklad je super co robi skrob, ale lepsie by bolo keby mal galeriu na postimage a odtial sa to linkovalo na plne verzie.

**Comment by MikkCZ** [comment]
https://postimage.io/site-plugins/phpbb.php
