### ISSUE TITLE
Zviditelnit obsah na domovské stránce

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#7]
V tuto chvíli je celá domovská stránka "vítací" pouze s menu a odkazy na články až úplně dole. Nenabízí tak nic zajímavého a moc na ní není vidět, co se třeba stalo nového.

**Comment by MikkCZ** [comment]
> neviem si to dosť dobre predstaviť ako? ale ÁNO, ak bude rozumný návrh
> takto je celá tá "úvodná" stránka podľa mňa krok vedľa, vôbec tam nejdem, v prehliadači mám záložku až na .../aktuality

**Comment by redhawk75** [comment]
suhlasim s Kamowskim.
podla mna uvodna strana je mrtva, stacilo by o tom ze su stranky komunity a spravit tam radsej prehlad clankov a postov vo fore (teraz je to az na dalsom)

**Comment by AnickaT** [comment]
Za mě ANO, dobrý nápad. Určitě na stránku dát aktuality (články, návody, události ze světa LinuxMint?) a co se aktuálně řeší na fóru LinuxMint. Opět souhlas s Kamowskim.

**Comment by ondrejkolin** [comment]
Úvodní stranu bych předělal ... 1) Musí být jasně vidět, cože LM vlastně je 2) pro každodenní návštěvníky hodit seznam akt. textů

**Comment by MikkCZ** [comment]
Chcete někdo udělat nějaký návrh, klidně načrtnout na papír, jak by to mohlo vypadat? Než se do toho já nebo kdokoliv pustí.

**Comment by MikkCZ** [comment]
Ve volné chvíli jsem upravil obsah na hlavní stránce, aby byly vidět widgety s posledními články.

**Comment by MikkCZ** [comment]
Chceme tam dát ještě něco navíc?
