### ISSUE TITLE
Zjednodušit menu

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#8]
Menu si zaslouží zjednodušení tak, aby nemělo tolik zanořování.

**Comment by MikkCZ** [comment]
> NIE - takto to mne vyhovuje, menu sa v priebehu času menilo, aj teraz tam admin robil nejaké úpravy, je to OK

**Comment by AnickaT** [comment]
Souhlas s Kamowskim. Sice je to zdánlivá nevýhoda více zanořené menu, na druhou stranu když se to víc ořeže, kam se pak budou "škatulkovat" ty věci co tam jsou...
