### ISSUE TITLE
Deduplikovat obsah

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/ukoly-a-wiki#9]
Nekontroloval jsem, v jakém je to stavu, ale na webu máme v článcích docela dost návodů apod. Možná jsou někde duplicity s wiki.

**Comment by MikkCZ** [comment]
A nejsou to jen články, ale i stránky na webu jako takové.

**Comment by redhawk75** [comment]
suhlas

**Comment by kamowski** [comment]
k článkom:
ak aj sú duplicity, bude to tým, že najprv vznikol článok a potom sa dostal do wiki
nemazal by som ani jednu kópiu, 
wiki je wiki ale pod článkom, aj starým, je možné diskutovať, komentovať, ....

**Comment by MikkCZ** [comment]
Když se koukám na obsah wiki, jsou to povětšinou prosté kopie z http://wiki.ubuntu.cz/, možná i v rozporu se současnou [licencí](https://creativecommons.org/licenses/by/4.0/), ale to raději ponechme stranou.

**Comment by MikkCZ** [comment]
Vůbec uvidíme podle #42.

**Comment by MikkCZ** [comment]
Viz #43.
